# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mealprep_db
spring.datasource.username=mealprep_user
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# disable cache for dev purpose
spring.thymeleaf.cache=false
spring.freemarker.cache=false
spring.mustache.cache=false
spring.groovy.template.cache=false
spring.mvc.view.cache=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
